abis/Registry.ts, contracts/Registry.sol, package.json, test/Registry.ts, yarn.lock
Registry contract created with:
Write methods:
- `registerReferrer` (owner only)
- `registerReferral`
Read methods:
- `getReferrers` for a given protocol
- `getUsers` for a given protocol, referrer pair
- `getRewardRate` for a given protocol, referrer pair
`npx hardhat compile` to create the ABI (I cleaned up output to what it is now)
Unit tests added
=> feat(registry): Create v0 Registry contract

.eslintrc.js, scripts/calculateRevenue/calculateRevenue.ts, scripts/calculateRevenue/protocols/beefy.ts, scripts/calculateRevenue/protocols/index.ts, scripts/types.ts
This is the first PR in a chain to get an initial version of the Beefy revenue attribution script working. See this [closed PR](https://github.com/mobilestack-xyz/funding-layer/pull/6#issue-2778995969) for a description/high-level overview of what this will eventually look like; I closed that PR in favor of a series of smaller PRs. I recommend reading the overview linked above to get a sense of what exactly these PRs are working towards.
This PR introduces a skeleton framework for writing handlers for calculating revenue attribution for different protocols.
=> feat(revenue): Add initial skeleton revenue script

README.md, scripts/fetch-referrals.ts, scripts/protocol-filters/beefy.test.ts, scripts/referrals.test.ts, scripts/referrals.ts, scripts/types.ts, scripts/utils.ts
* fetches referrals from all networks (because if two different frontends both refer a user to a protocol on different chains we need to determine which one did it first)
* removes duplicate referals
=> feat(referral): fetch referrals from registry contract

scripts/calculateRevenue/protocols/beefy.test.ts, scripts/calculateRevenue/protocols/beefy.ts, scripts/utils/fetchWithTimeout.ts
Follow-up PR to #7. This PR introduces a helper function that calls a public [Beefy API endpoint](https://databarn.beefy.com/api/v1/documentation/static/index.html) in order to get historical vault TVL (in USD) in 15-minute increments. This will be used later on when calculating a user's share of a vault at any given time, as the denominator in the ratio.
=> feat(revenue): Add Beefy helper to fetch vault TVL

README.md, scripts/deploy.ts
This makes it easier to pipe the environment around. E.g.,
```
eval `yarn hardhat run scripts/deploy.ts`
```
=> chore: "shell" mode for deploy script

abis/Registry.ts, scripts/deploy.ts, test/Registry.ts
This PR does a couple of small things:
- update the abi to account for the latest contract changes
- update the Registry tests to use `stringToHex` for the byte32 type conversion (`toBytes` returns a `ByteArray` which is causes typescript errors when used with `encodeFunctionData`)
- ensure command to verify contract is always printed for the deploy script as folks may want to verify the contracts when deployed locally
Note that we need to add `as const` to the end of the abi variable, but I did not do that here because it generates too many errors (the funding scripts all need to be updated to account for the contract changes, I spent some time on this but wasn't sure I was making the best changes)
=> chore: update abi and tests

scripts/calculateRevenue/protocols/beefy/helpers.test.ts, scripts/calculateRevenue/protocols/beefy/helpers.ts, scripts/calculateRevenue/protocols/beefy/types.ts, scripts/calculateRevenue/protocols/types.ts, scripts/calculateRevenue/protocols/utils/events.test.ts, scripts/calculateRevenue/protocols/utils/events.ts
Creates a more generic `fetchEvents` function to fetch all events of a certain event name from a specific contract for a specified time range.
Preparation for in flight tickets that also query events from different contracts
* https://linear.app/valora/issue/ENG-175/tvl-calculation-for-somm
* https://linear.app/valora/issue/ENG-176/transaction-volume-for-aerodrome
=> refactor(utils): make more generic functions for fetching blockchain events

README.md, scripts/calculateRevenue/protocols/index.ts, scripts/calculateRevenue/protocols/somm/getEvents.test.ts, scripts/calculateRevenue/protocols/somm/getEvents.ts, scripts/calculateRevenue/protocols/somm/getVaults.ts, scripts/calculateRevenue/protocols/somm/index.test.ts, scripts/calculateRevenue/protocols/somm/index.ts, scripts/calculateRevenue/protocols/somm/types.ts, scripts/deploy.ts, scripts/protocolFilters/index.ts, scripts/protocolFilters/somm.ts, scripts/types.ts
Calculates mean TVL by finding the users current LP token tvl, all tvl changing events (deposits and withdraws), and working backwards to determine the user's TVL over time.
TODO's in other tickets: 
* returning the daily mean tvl in usd instead of the mean tvl in LP token
* adding more vaults
* adding a filter function to filter out users that were using somm before the divvi event.
https://linear.app/valora/issue/ENG-175/tvl-calculation-for-somm
=> feat(somm): mean tvl for somm

scripts/calculateRevenue/protocols/beefy/helpers.test.ts, scripts/calculateRevenue/protocols/beefy/helpers.ts, scripts/calculateRevenue/protocols/somm/getEvents.test.ts, scripts/calculateRevenue/protocols/somm/getEvents.ts, scripts/utils/index.ts
Should help save a few network calls while running the script.
also based on pr feedback: https://github.com/divvi-xyz/divvi-protocol-v0/pull/44#discussion_r1988115519
=> refactor(getBlock): make client.getBlock a memoized function

contracts/RewardPool.sol, test/RewardPool.ts
The Reward pool contract is unable to deploy with the Owner other than the deployer.
The problem is with granting Manager role during initialization. After the owner is set, the checks in `grantRole()` prevent deployer from granting the Manager role. This is inconvenient since we want to set both Owner and Manger during contract initialization.
This PR fixes it by replacing the `grantRole()` call during initialization with an internal `_grantRole()` to bypass role checks.
The tests, sadly, didn't cover the case to surface earlier. 
* Updated unit tests
Related to RET-204
=> fix: fix deployment with owner other than deployer

README.md, tasks/mockToken.ts, tasks/rewardPool.ts
Use the `contract:action` naming convention for all tasks, similar to the one implemented for the Registry task. 
It seems natural to put the contract name first, as we group tasks per contract, and different contracts may have different associated tasks.
This makes this naming approach consistent.
Resulting tasks:
* `registry:deploy`
* `registry:populate`
* `reward-pool:deploy`
* `reward-pool:upgrade`
* `mock-token:deploy`
=> chore: use contract:action naming convention in tasks

package.json, renovate.json5, yarn.lock
Downgrade Chai [HH19: Hardhat config with .js extension in an ESM project](https://hardhat.org/hardhat-runner/docs/errors#HH19) - https://github.com/NomicFoundation/hardhat/issues/4762.
=> chore(deps): downgrade chai to ^4.5.0

tasks/helpers/populateRegistry.ts
There were 3 protocolIds for `leefy` but only 2 rewardRates, added a third one and running `yarn hardhat --network localhost registry:populate` worked.
=> fix: populateRegistry failing with array index out of bounds

scripts/utils/referrals.ts
When runniing the scripts e2e, i found that the fetchReferrals script wasn't returning any referrals. I then saw the `topics` value was incorrect, and it is because we are using the old abi to generate the topic hash.
Command for reference: 
```
yarn ts-node scripts/fetchReferrals.ts --protocol=celo-transactions --output-file=rewards/celo-transactions/referrals.csv
```
Related to ENG-332
=> fix: referral script using wrong topic for hypersync query

.openzeppelin/celo.json, scripts/calculateRevenue/protocols/utils/events.ts, scripts/calculateRewards/e2eTestRewards.ts
For [ENG-334](https://linear.app/valora/issue/ENG-334/setup-rewards-entity-for-e2e-testing).
Adds in a script for calculating rewards for the e2e test campaign according to [this doc](https://docs.google.com/document/d/1xVe0DgNJ39KbBlyBrKmqsuhHnLCMYOJ0J9OzOpM93rU/edit?tab=t.0).
The e2e Reward Pool is deployed on Celo [here](https://celoscan.io/address/0x5782CaB7e3dC7991d15665A413aa64a52E62B769).
The e2e Campaign Provider Safe is [here](https://app.safe.global/home?safe=oeth:0xDe9D9522241baB65D432B3aEbee29e378de5856E).
The e2e Builder Safe is [here](https://app.safe.global/home?safe=oeth:0xfC6Eb1Fb78350809591180bf5566915A32f5a515).
The Reward Pool has been loaded with 1B [MockToken](https://celoscan.io/address/0x91652b5c6a30e813262b31868885B5BFEB134354).
Since we don't have a script yet …
=> feat(testing): Add in reward calculation script for e2e testing

scripts/calculateRevenue.ts, scripts/calculateRevenue/protocols/aave/blockchainData/index.ts, scripts/calculateRevenue/protocols/aave/blockchainData/reserveFactor.ts, scripts/calculateRevenue/protocols/aave/blockchainData/subgraph.ts, scripts/calculateRevenue/protocols/arbitrum/index.ts, scripts/calculateRevenue/protocols/celo-pg/index.ts, scripts/calculateRevenue/protocols/celoTransactions/index.ts, scripts/calculateRevenue/protocols/utils/events.test.ts, scripts/calculateRevenue/protocols/utils/events.ts, scripts/calculateRevenue/protocols/utils/networks.test.ts, scripts/calculateRevenue/protocols/utils/networks.ts, scripts/calculateRewards/e2eTestRewards.ts, scripts/calculateRewards/proofOfImpact.ts, scripts/getDivviIntegrators.ts
As the title says. 
This fixes subtle off-by-one errors we had due to HyperSync / RPC node not treating the "to block" the same way (exclusive vs inclusive).
Also `startTimestamp` is now guaranteed to be included and `endTimestamp` excluded.
The main changes are in `events.ts` and its unit tests. The rest is adapting existing code to call the new method.
Part of ENG-365
=> fix(scripts): introduce getBlockRange and standardize to [start,end) block ranges

.gitignore, scripts/calculateRevenue.ts, scripts/calculateRewards/celoPG.ts, scripts/calculateRewards/e2eTestRewards.ts, scripts/calculateRewards/proofOfImpact.test.ts, scripts/calculateRewards/proofOfImpact.ts, scripts/fetchReferrals.ts, scripts/getDivviIntegrators.ts, scripts/utils/createSafeTransactionsBatch.test.ts, scripts/utils/createSafeTransactionsBatch.ts, scripts/utils/dateFormatting.ts
We need to run 3 scripts to do the reward distributions, and each script requires us to declare the input and output file paths. Each file path depends on the reward period start and end times. This is cumbersome and there is room for copy and paste errors when creating the file paths.
This PR proposes the following changes:
- we pass the start and end timestamp to all scripts (currently not needed for `fetchReferrals`) - this might make it easy to eventually automate and declare these variables one time?
- the input and output file paths are determined in code and use the start and end timestamps + protocol
- the folder names will look like `rewards/{{protocol}}/2025-05-08T00-00-00Z_2025-05-15T00-00-00Z` which i personally find more readable than 2 unix timestamps, and still allows …
=> refactor: remove input and output file name args for scripts

scripts/fetchReferrals.ts, scripts/protocolFilters/index.ts
This PR fixes a couple things:
- parse the allowList into an `Address` array
- pass allowList all the way to the filter
Also, add the allowList to the reward directory because it should be checked in.
=> fix: ensure builder allowlist format and passed to filter

scripts/utils/dateFormatting.ts
A well-defined format is useful because it's parseable by js Date or GNU date. We also need more precision for some programs we're running, like Divvi integration rewards.
=> chore: use ISO 8601 timestamps for directories

scripts/calculateRevenue.ts, scripts/fetchReferrals.ts
A bug snuck through where we were creating a date with a timestamp in seconds, when it expects milliseconds. This caused the calculateRevenue script to calculate starting from the unix epoch instead of the reward period specified.
=> fix: referral buffer time incorrect conversion

scripts/calculateKpi.test.ts, scripts/calculateKpi.ts
I originally wanted to pass the handler in to the calculateKpiBatch function to facilitate testing, but when actually running the script in CI where we parallelise the campaigns, the logs got very confusing to read. So this PR adds the protocol to the printed logs.
Related to ENG-392
=> refactor: print protocol name in calculateKpi logs

scripts/calculateKpi.test.ts, scripts/calculateKpi.ts, scripts/calculateKpi/protocols/utils/events.ts
When running the calculateKpi scripts on CI, it was the _getNearestBlock function that started failing. On closer inspection, it seems envio has no rate limits but DefiLlama has a rate limit of 500 requests/min. In the worst case, we call _getNearestBlock for every user in the reward period if they were referred within the period (i.e. we need to get the block corresponding to their referral)
This PR adds:
- better error messaging on _getNearestBlock (the error response was previously logged as `[object Object]`
- delay after every kpi batch transaction to keep requests under the rate limit 
Related to ENG-392
=> chore: ensure delays to avoid rate limits in calculateKpi

scripts/fetchReferrals.ts, scripts/protocolFilters/aave.ts, scripts/protocolFilters/aerodrome.ts, scripts/protocolFilters/arbitrum.ts, scripts/protocolFilters/beefy.ts, scripts/protocolFilters/celo-pg.ts, scripts/protocolFilters/celoTransactions.test.ts, scripts/protocolFilters/celoTransactions.ts, scripts/protocolFilters/fonbnk.ts, scripts/protocolFilters/index.ts, scripts/protocolFilters/rhino.ts, scripts/protocolFilters/scoutGameV0.ts, scripts/protocolFilters/somm.ts, scripts/protocolFilters/velodrome.ts, scripts/types.ts
Refactor filter logic to accept multiple filtering params as a separate object, instead of positional arguments.
Before:
```
filter(event, allowlist, blacklist) // easy to accidentally twist the lists
```
After:
```
filter(event, { allowlist, blacklist }) // explicit and sound
```
No existing behavior is changed.
CI
Related to ENG-388
=> chore(refactor): refactor filter logic for multiple params

.github/workflows/calculate-and-upload-KPIs.yaml
it takes over 1 hr to run now, so every hour is too frequent
=> chore: run the KPI workload every 2 hours

.github/workflows/calculate-and-upload-KPIs.yaml, package.json, scripts/calculateKpi.ts, scripts/calculateKpi/protocols/utils/events.ts, scripts/fetchReferrals.ts, yarn.lock
This PR adds the `bottleneck` npm package to manage the DefiLlama rate limit at the api request level. This is much more efficient than managing at the kpi calc level, since some calculations don't require a request to DefiLlama.
Example of a [job](https://github.com/divvi-xyz/divvi-protocol-v0/actions/runs/15451499250/job/43494472674?pr=220) running with this change, which took ~15 minutes. It ran the same logic as the other jobs in the CI which take ~90 minutes.
With this change, I could also change the frequency of the scheduled calc and upload job back to 1 hour.
Related to ENG-414
=> feat: improve DefiLlama rate limit handling

scripts/utils/referrals.ts
Without this change the scripts don't pick up the referrals correctly, oops 🙈
Related to ENG-415
=> fix: missing Lisk campaign provider id

scripts/calculateRewards/celoPG.ts, scripts/calculateRewards/getReferrerMetricsFromKpi.test.ts, scripts/calculateRewards/getReferrerMetricsFromKpi.ts, scripts/calculateRewards/liskV0.ts, src/proportionalPrizeContest.test.ts, src/proportionalPrizeContest.ts
We want to show the number of referrals per campaign per reward period, however Dune's live fetch has a 4MiB response [limit](https://docs.dune.com/query-engine/Functions-and-operators/live-fetch#limits). Unfortunately for more popular campaigns, any .json file that has one entry per user will probably exceed this limit. The kpi.json for celo pg campaign is over 6MB.
This PR adds a `numReferrals` property per builder in the rewards.json. This file is already uploaded during the upload CI job. The reward calculation scripts all need to calculate the raw kpi value per builder + the total kpi value, so i abstracted this logic to a function and added a step to also return the number of referrals.
Not included in this PR: number of referrals per network for Scout Game.
Related to ENG-444 and …
=> chore: add number of referrals to reward.json

.github/workflows/calculate-and-upload-KPIs.yaml, scripts/calculateKpi.ts, scripts/uploadCurrentPeriodKpis.ts
This PR has some misc fixes:
- the protocol input in the manual dispatch should be optional (undefined = calculate for all campaigns)
- remove some noisy logs
- fix some incorrect logs
=> fix: upload kpis CI job optional input and logs

scripts/calculateKpi.ts, scripts/calculateKpi/protocols/arbitrum/index.ts, scripts/calculateKpi/protocols/celo-pg/index.ts, scripts/calculateKpi/protocols/celoTransactions/index.ts, scripts/calculateKpi/protocols/liskV0/index.ts, scripts/calculateKpi/protocols/scoutGameV0.ts, scripts/calculateKpi/protocols/utils/networks.test.ts, scripts/calculateKpi/protocols/utils/networks.ts, scripts/calculateRewards/celoPG.ts, scripts/calculateRewards/proofOfImpact.ts, scripts/calculateRewards/scoutGameV0.ts, scripts/types.ts, src/resultDirectory.ts
Updated `breakdown` to `metadata` to be more generic with what it will have (not just a breakdown of kpi, in this case is # transaction when kpi is gas).
**Manual testing:**
```
ts-node scripts/uploadCurrentPeriodKpis.ts --dry-run --protocol celo-pg
```
```
[
...
{
"referrerId": "0xe6e6c0ddf053822bbbc1f39218f30ea25fca58dd",
"rewardAmount": "176398364831532259500",
"referralCount": 7925,
"kpi": "47323465",
"linearProportion": "0.00352796",
"powerProportion": "0.03962855",
"linearReward": "176398364831532259500.00000000",
"powerReward": "0.00000000",
"totalTransactions": 865
},
{
"referrerId": "0x99342d3ce2d10c34b7d20d960ea75bd742aec468",
"rewardAmount": "39195206284652732500",
"referralCount": 68,
"kpi": "10515137",
"linearProportion": "0.00078390",
"powerProportion": "0.01868002", …
```
=> feat: Add total transaction count to celo-pg rewards json

.github/workflows/calculate-and-upload-KPIs.yaml
This PR adds a slack notification to the on-call slack channel when the periodic kpi calculation and upload CI fails. I've been keeping an eye on this workflow for the last few weeks and it is quite stable, so I don't expect this alert to fire often.
I followed the integration steps [here](https://tools.slack.dev/slack-github-action/sending-techniques/sending-data-slack-incoming-webhook/post-inline-text-message). Example of slack alert is [here](https://valora-app.slack.com/archives/C02N3AR2P2S/p1750245850795729).
Fixes ENG-392
=> chore: add slack notification on kpi upload CI failure

scripts/uploadCurrentPeriodKpis.ts
This change uploads the generated safe-transactions.json file during the kpi calculation CI workflow. For campaigns that do not require an inclusion list at the time of reward calculation (i.e. all current campaigns), this change makes it so that you can download the file from the CI directly without having to run any scripts locally. One less step for reward distributions :)
=> feat: upload safe txs in CI

scripts/calculateKpi/protocols/tetherV0/parseReferralTag/getTransactionInfo.ts, scripts/calculateKpi/protocols/utils/events.ts, scripts/utils/index.ts, scripts/utils/networks.ts
I forgot to add viem client config for the new networks supported by the Tether campaign. I expected typescript to help us with where to add config, but this `Partial` type got in the way. This PR removes `Partial` as much as possible, and adds the missing viem client config.
=> fix: ensure supported networks have viem client config

scripts/calculateKpi/protocols/tetherV0/parseReferralTag/getReferrerIdFromTx.ts
We expect this to fail often so the console.warns aren't very helpful
=> chore: silence consoles in getReferrerIdFromTx.ts

scripts/findQualifyingReferral/qualifyingNetworkReferral.test.ts, scripts/findQualifyingReferral/qualifyingNetworkReferral.ts
Locally tested with:
```
yarn ts-node ./scripts/fetchReferrals.ts --protocol base-v0 --start-timestamp 2025-06-30T00:00:00Z --end-timestamp 2025-07-30T00:00:00Z
```
(took 13 minutes, much better than before optimization)
=> feat(qualifying-network-referral): more optimizations

scripts/calculateRewards/tetherV0.ts
`totalTransactions` was 0, kpi is just number of qualifying txs, so just set to that.
=> fix: Fix tether totalTransactions field in reward json

.github/workflows/calculate-and-upload-KPIs.yaml, scripts/calculateKpi.ts
tether campaign looks for referrer tag in all txs so no need to start part way through the period, this reduces need for  multiple defi llama calls to get start block which were very slow
=> chore: Update workflow runtime and have tether use period startTimestamp

scripts/uploadCurrentPeriodKpis.ts, src/campaigns.ts
Fixes periodic upload job failure [here](https://github.com/divvi-xyz/divvi-protocol/actions/runs/16840464907/job/47710204669). This campaign was not in the upload script campaign list, so reward periods didn't get moved over to new campaigns file [here](https://github.com/divvi-xyz/divvi-protocol/pull/365/files#diff-e2e59ccdf441770c6a95eff037bbf79e3225a6df2e943e145ce534a3886943c4). The campaign is done so can just be removed.
Also added a check in the periodic script to just skip campaigns with no rewards periods
=> chore: Remove past campaign with no reward periods

scripts/uploadCurrentPeriodKpis.ts
These are delayed and will likely change. I have a refactor patch set for scripts/uploadCurrentPeriodKpis.ts and want to exclude including them in that work.
=> chore: remove mantle and morph from periodic runner

contracts/RewardPool.sol, contracts/rewardFunctions/IRewardFunction.sol, contracts/rewardFunctions/LinearReward.sol, contracts/rewardFunctions/SqrtReward.sol, test/LinearReward.ts, test/RewardPool.ts, test/SqrtReward.ts
Follow up based on https://github.com/divvi-xyz/divvi-protocol/pull/462#discussion_r2311590339 
This updates the RewardPool and related contracts to use `referrer` consistently over `user` and `referrerAddress`.
=> refactor(contracts): use referrer consistently over user / referrerAddress

contracts/RewardPool.sol, test/RewardPool.ts
In #472 I initially forgot to call `setDefaultOwner` and after upgrading an existing `RewardPoolFactory`, the created reward pool had its owner set to the 0 address.
This prevents it.
=> fix(RewardPool): prevent 0 address with owner and/or manager
