scripts/calculateRevenue/protocols/somm/dailySnapshots.test.ts, scripts/calculateRevenue/protocols/somm/dailySnapshots.ts, scripts/calculateRevenue/protocols/somm/index.test.ts, scripts/calculateRevenue/protocols/somm/index.ts, scripts/calculateRevenue/protocols/somm/types.ts
https://linear.app/valora/issue/ENG-201/somm-return-daily-mean-tvl-in-usd
* Takes advantage of a Somm API that returns daily snapshots of the price per share of the vault token and the USD price of the underlying asset
=> feat(somm): return revenue in USD

.env.example, package.json, scripts/calculateRevenue/protocols/arbitrum/index.ts, scripts/calculateRevenue/protocols/celo/index.ts, scripts/calculateRevenue/protocols/index.ts, scripts/calculateRevenue/protocols/utils/networks.test.ts, scripts/calculateRevenue/protocols/utils/networks.ts, scripts/protocolFilters/arbitrum.ts, scripts/protocolFilters/celo.ts, scripts/protocolFilters/index.ts, scripts/types.ts, scripts/utils/index.ts, scripts/utils/networks.ts, yarn.lock
Gets all transaction fees for registered users on a specific network.
1. Grab an API key from https://envio.dev/app/api-tokens
2. Set your .env following `.env.example`.
3. Run the following scripts: 
```bash
yarn ts-node ./scripts/fetchReferrals.ts --protocol arbitrum
yarn ts-node ./scripts/calculateRevenue.ts --protocol arbitrum --startTimestamp 1647595987000 --endTimestamp 1741899467000
```
Resulting `arbitrum-revenue.csv`
```
investor,0x15B5f5FE55704140ce5057d85c28f8b237c1Bc53,1740013389
```
=> feat: calculate gas fees for blockchain networks

jest.config.js, package.json, scripts/setupTestnet.ts, src/tsconfig.json, test/Registry.ts, tsconfig.json, tsconfig.test.json
I noticed the test folder wasn't being typechecked.
Then I fixed the new issues reported.
=> chore: fix tsconfig ignoring tests

README.md, contracts/DivviRegistry.sol, hardhat.config.ts, tasks/divviRegistry.ts, tasks/helpers/deployHelpers.ts, tasks/registry.ts, tasks/rewardPool.ts
This PR:
- adds deploy and upgrade tasks for DivviRegistry (moving some checks around to reduce duplicated code)
- updates README
- removes unused arguments in DivviRegistry
Related to ENG-234
=> chore: add deploy tasks for DivviRegistry

contracts/DivviRegistry.sol, test/DivviRegistry.ts
=> refactor: use CAIP-2 chainId in DivviRegistry

README.md, docs/contracts.md
=> chore: update readme for DivviRegistry deployment

contracts/Registry.sol, package.json
It was using the `package.json` prettier config, instead of the `.prettierrc.js` which contains the solidity plugin.
=> chore: format sol files with prettier

scripts/getDivviIntegrators.ts
Tested with the following command:
```
yarn ts-node ./scripts/getDivviIntegrators.ts --reward-pool=0xEdb51A8C390fC84B1c2a40e0AE9C9882Fa7b7277 --reward-amount=200 --start-timestamp=1745107200000 --end-timestamp=1746403200000
```
Didn't have the actual RewardPool address since it hasn't been deployed so just used a random one, but doesn't matter since that is only used for finding people who have received rewards and no one has. Script found 2 consumers who have registered referrals between the timestamps (one was me doing a test), and found 16 builders who have registered agreement with the Divvi Integration Reward entity.
=> chore: Get script in working state and clean up

scripts/calculateRewards/proofOfImpact.test.ts, scripts/calculateRewards/proofOfImpact.ts
=> chore: proof-of-impact reward script

rewards/divvi-integrators/1745107200000-1747247130000/safe-transactions.json
```
START=1745107200000
END=1747243524718
yarn ts-node ./scripts/getDivviIntegrators.ts \
--start-timestamp=$START \
--end-timestamp=$END \
--safe-transactions-file=rewards/divvi-integrators/${START}-${END}/safe-transactions.json
```
=> chore: another divvi integrator reward processing

rewards/divvi-integrators/2025-04-20T00:00:00.000Z_2025-05-16T04:30:30.000Z/safe-transactions.json
```
yarn ts-node ./scripts/calculateRewards/divviIntegration.ts \
--start-timestamp=$START \
--end-timestamp=$END \
--safe-transactions-file rewards/divvi-integrators/2025-04-20T00\:00\:00.000Z_2025-05-16T04\:30\:30.000Z/safe-transactions.json
```
=> chore: integrator rewards

rewards/divvi-integrators/2025-04-20T00:00:00.000Z_2025-05-16T20:14:55.000Z/safe-transactions.json
```
yarn ts-node ./scripts/calculateRewards/divviIntegration.ts \
-s 2025-04-20T00:00:00.000Z \
-e 2025-05-16T20:14:55.000Z \
--safe-transactions-file rewards/divvi-integrators/2025-04-20T00:00:00.000Z_2025-05-16T20:14:55.000Z/safe-transactions.json
```
=> chore: integration reward run

scripts/fetchReferrals.ts
=> chore: add a --datadir argument to fetchReferrals

scripts/calculateRevenue.ts, scripts/calculateRewards/celoPG.ts, scripts/calculateRewards/proofOfImpact.ts
Similar to badd415c2ec4c7f205b41c77f64b1e468d7a42f4
=> chore: more --datadir support

scripts/calculateRewards/proportionalPrizeContest.test.ts, scripts/calculateRewards/proportionalPrizeContest.ts
This is the calculation we use for proof-of-impact, PG, and scout game. I'll update those to use this code in a follow-on.
=> chore: add a proportionalPrizeContest reward

rewards/divvi-integrators/2025-03-01T08:00:00.000Z_2025-05-20T20:45:40.000Z/safe-transactions.json
```
yarn ts-node scripts/calculateRewards/divviIntegration.ts \
-s 'Sat Mar 01 2025 08:00:00 GMT+0000' \
-e `date --iso-8601=seconds`
```
=> chore: run integration rewards

scripts/protocolFilters/index.ts
This is a helpful optimization for filters that do IO. E.g., call hypersync
=> chore: add batching for await filtering calls

scripts/calculateRewards/proofOfImpact.ts, src/resultDirectory.test.ts, src/resultDirectory.ts
Replace the copy-pasting file path construction before I start adding more results files.
=> refactor: "ResultDirectory"

docs/contracts.md
=> chore(docs): add staging reward pool address on Celo

src/resultDirectory.test.ts, src/resultDirectory.ts
This is to faciltiate livefetch usage on dune.
=> feat: save JSON results too

scripts/calculateRewards/celoPG.ts
Similar to 7d496d753dee01b4821b21e0ed75e8e082ac8a9c
=> chore(celoPG): reward `main` takes a ResultDirectory argument

scripts/calculateRewards/celoPG.ts, scripts/uploadCurrentPeriodKpis.ts
=> chore: option to calculate and upload data aggregated by referralId ("rewards")

scripts/uploadCurrentPeriodKpis.ts
=> feat: add lisk campaign to data upload CI

scripts/uploadCurrentPeriodKpis.ts
This PR uploads the calculated campaign data after every campaign, rather than uploading all data for all campaigns at once. Given that there are network requests with each user's kpi calculation, it seems more robust to upload data as soon as we get it (so that errors in calculations for one campaign doesn't block uploading another campaign's kpis if already calculated)
=> refactor: upload campaign data per campaign

scripts/calculateKpi/protocols/utils/networks.ts
=> fix: Fix total transaction count

.github/workflows/calculate-and-upload-KPIs.yaml, scripts/uploadCurrentPeriodKpis.test.ts, scripts/uploadCurrentPeriodKpis.ts
As discussed in retro yesterday
=> chore: calculate kpi manual dispatch CI accepts multiple protocols

.eslintrc.js, scripts/calculateKpi/protocols/aave/blockchainData/oracle.ts, scripts/calculateKpi/protocols/aave/index.test.ts, scripts/calculateKpi/protocols/aave/index.ts, scripts/calculateKpi/protocols/rhino/index.ts, scripts/calculateKpi/protocols/somm/getVaults.test.ts, scripts/calculateKpi/protocols/utils/events.test.ts, scripts/calculateRewards/baseV0.ts, scripts/calculateRewards/celoPG.test.ts, scripts/calculateRewards/celoPG.ts, scripts/calculateRewards/liskV0.ts, scripts/calculateRewards/listV0.test.ts, scripts/calculateRewards/mantleV0.ts, scripts/calculateRewards/proofOfImpact.test.ts, scripts/calculateRewards/proofOfImpact.ts, scripts/calculateRewards/scoutGameV0.ts, scripts/calculateRewards/slices.ts, scripts/calculateRewards/tetherV0.ts, src/proportionalPrizeContest.test.ts, src/proportionalPrizeContest.ts
Backtracks 2cc1719e0355defd642eed487a1ecead374f8b7f
=> chore: address lint warnings

docs/contracts.md
Following the work done last week to consolidate the safe wallets.
=> chore: update contract owner addresses

scripts/calculateKpi/protocols/tetherV0/parseReferralTag/parseReferral.ts
See [this Slack thread](https://valora-app.slack.com/archives/C08V2CVD0M9/p1754329211210329) for more context.
This logic was copied and adapted/simplified from [parseReferral.ts](https://github.com/divvi-xyz/divvi-relayer/blob/main/src/endpoints/submitReferral/parseReferral.ts#L200) in the relayer repo.
=> feat(referrals): Update referral parsing to support V0 referral tags

docs/calculate-kpi/aave.md, docs/calculate-kpi/aerodrome.md, docs/calculate-kpi/arbitrum.md, docs/calculate-kpi/baseV0.md, docs/calculate-kpi/beefy.md, docs/calculate-kpi/celo-pg.md, docs/calculate-kpi/celoTransactions.md, docs/calculate-kpi/fonbnk.md, docs/calculate-kpi/liskV0.md, docs/calculate-kpi/mantleV0.md, docs/calculate-kpi/morph.md, docs/calculate-kpi/rhino.md, docs/calculate-kpi/scoutGameV0.md, docs/calculate-kpi/somm.md, docs/calculate-kpi/tetherV0.md, docs/calculate-kpi/velodrome.md, scripts/calculateKpi/protocols/tetherV0/parseReferralTag/getReferrerIdFromTx.ts, scripts/fetchReferrals.ts, scripts/findQualifyingReferral/qualifyingNetworkReferral.test.ts, scripts/findQualifyingReferral/qualifyingNetworkReferral.ts
To test:
```
yarn ts-node ./scripts/fetchReferrals.ts --protocol base-v0 --start-timestamp 2025-06-30T00:00:00Z --end-timestamp 2025-07-30T00:00:00Z
```
=> chore: work towards optimizing qualifyingNetworkReferral

scripts/utils/divviRewardsExcludedReferrers.ts
* turns back on fetching ofac addresses to exclude them from receiving rewards
* cache to reduce the number of calls
https://linear.app/valora/issue/ENG-582/re-enable-ofac-address-fetching
=> fix(ofac): turn ofac back on and cache to reduce the number of calls and hopefully avoid 403's

cloud-functions/endpoints/redistributeValoraRewards/proposeSafeClaimRewardTx.ts
Safe doesn't like anything that isn't checksummed
=> fix(redistributeValoraRewards): checksum reward pool address

scripts/calculateRewards/celo-pg-s1.ts
I will update the CeloPG asks as a follow-on.
=> chore: basic rewards script for celo-pg-s1

scripts/calculateRewards/celoPGS1.ts, src/campaigns.ts
=> refactor(celo-pg): speciy KPI files to use for stage calculation

src/campaigns.ts
Per https://docs.google.com/document/d/1Iaiq4-Hr6Otg8gS_V9qMKXOPyw20InThmgdU-9cMkfU/edit?tab=t.0
=> feat(campaigns): update tether campaign reward periods

src/campaigns.ts
=> chore: update celo pg s1 cycle 2 exclude list

src/celoPGRewards.test.ts, src/celoPGRewards.ts
This is for informational purposes.
=> chore: add isExcluded to celo pg s1 reward results

.github/workflows/calculate-and-upload-KPIs.yaml, src/campaigns.ts
https://linear.app/valora/issue/ENG-657/ability-for-campaign-managers-to-update-an-excluded-list
paired with https://github.com/divvi-xyz/divvi-dapp/pull/392
=> feat(campaings): Fetch excluded referrers from google sheets
